-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS Ingredient CASCADE;
DROP TABLE IF EXISTS ReceipeIngredient CASCADE;
DROP TABLE IF EXISTS Receipe CASCADE;
DROP TABLE IF EXISTS Category CASCADE;
DROP TABLE IF EXISTS Review CASCADE;
DROP TABLE IF EXISTS Member CASCADE;