-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS Ingredient CASCADE;
DROP TABLE IF EXISTS RecipeIngredient CASCADE;
DROP TABLE IF EXISTS Recipe CASCADE;
DROP TABLE IF EXISTS Category CASCADE;
DROP TABLE IF EXISTS Review CASCADE;
DROP TABLE IF EXISTS Member CASCADE;